# IS 4487 Lab 3

## Outline

Repeat exercises from Lab 2, but with the *SuperStore Retail Orders* dataset
- Loading installed packages
- Inspect data
- Explore plot types

<a href="https://colab.research.google.com/github/Stan-Pugsley/is_4487_base/blob/main/Labs/Scripts/lab_03_retailer_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Superstore Data Dictionary

 ORDER VARIABLES:
 - Order ID
 - Order Date
 - Order Year Month - Year and month of the order
 - Order Type - Was the order completed at a store or online? (Retail, Online)
 - Quantity - Quantity ordered for the product

 CUSTOMER VARIABLES:
 - Customer Name
 - City
 - State Province
 - Email

PRODUCT VARIABLES:
 - Product Name
 - Product Line - Category of the product (i.e. Bikes Phones)
 - Product Price - Price in US Dollars
 - Product Status - Current status of the product (Active, Inactive)

## Load Libraries

➡️ Assignment Tasks
- Load any necessary libraries

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
import pandas as pd
import numpy as np
import sklearn as sl

## Import Data into Dataframe

➡️ Assignment Tasks
- Import data from the SuperStore retail dataset into a dataframe (in GitHub go to Labs > DataSets)
- Describe or profile the dataframe

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/Stan-Pugsley/is_4487_base/main/Labs/DataSets/superstore_retail_orders.csv')
print (df)

df.describe()

       order_id  order_date order_year_month     customer_name  \
0         51188  2023-07-01          2023-07     Audrey Blanco
1         51187  2023-07-01          2023-07       Isaac Allen
2         51199  2023-07-02          2023-07        Ian Morgan
3         51241  2023-07-04          2023-07        Alexa Bell
4         51297  2023-07-08          2023-07        Casey Diaz
...         ...         ...              ...               ...
56038     74084  2024-06-29          2024-06        Ian Rogers
56039     74062  2024-06-29          2024-06   Marcus Anderson
56040     74065  2024-06-29          2024-06  Nathaniel Howard
56041     74038  2024-06-29          2024-06        Robin Sanz
56042     74110  2024-06-30          2024-06   Mallory Jimenez

                    city state_province                       email  \
0      North Cherylmouth  New Hampshire     audrey_blanco@email.com
1             Traceyland  West Virginia       isaac_allen@email.com
2              Dylanberg   South Dakota        ian_morgan@email.com
3         Lake Tracytown      Wisconsin        alexa_bell@email.com
4            Byrdchester    Mississippi        casey_diaz@email.com
...                  ...            ...                         ...
56038          Port Mark        Alabama        ian_rogers@email.com
56039     West Aprilfurt       Nebraska   marcus_anderson@email.com
56040      New Lindaview       Illinois  nathaniel_howard@email.com
56041    West Frankhaven       Arkansas        robin_sanz@email.com
56042        Dillonhaven       Maryland   mallory_jimenez@email.com

      order_type  quantity                                       product_name  \
0         Retail       3.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
1         Online       4.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
2         Online       5.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
3         Online       1.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
4         Online       1.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
...          ...       ...                                                ...
56038     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56039     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56040     Online       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56041     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56042     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...

      product_line  product_price product_status
0           Mobile         649.99         Active
1           Mobile         649.99         Active
2           Mobile         649.99         Active
3           Mobile         649.99         Active
4           Mobile         649.99         Active
...            ...            ...            ...
56038  Electronics         914.62         Active
56039  Electronics         914.62         Active
56040  Electronics         914.62         Active
56041  Electronics         914.62         Active
56042  Electronics         914.62         Active

[56043 rows x 13 columns]

           order_id       quantity  product_price
count  56043.000000   56004.000000   56043.000000
mean   61668.410578       3.348582    6198.309433
std     7508.142486     422.654112   35784.965255
min    45079.000000       1.000000       2.290000
25%    55644.500000       1.000000       7.950000
50%    61870.000000       1.000000     475.600000
75%    68097.000000       2.000000     914.620000
max    74147.000000  100000.000000  235481.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56043 entries, 0 to 56042
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          56043 non-null  int64
 1   order_date        56011 non-null  object
 2   order_year_month  56011 non-null  object
 3   customer_name     56043 non-null  object
 4   city              55569 non-null  object
 5   state_province    55569 non-null  object
 6   email             56043 non-null  object
 7   order_type        56043 non-null  object
 8   quantity          56004 non-null  float64
 9   product_name      56043 non-null  object
 10  product_line      56043 non-null  object
 11  product_price     56043 non-null  float64
 12  product_status    56043 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 5.6+ MB

## Prepare Data

➡️ Assignment Tasks
- Create a "revenue" variable and make sure it is a numeric datatype
- Remove rows with empty (NULL) values
- Locate outliers in at least two of the variables.   Filter them out if they are mistakes; keep them if they are exceptional cases.

In [24]:
df['revenue'] = pd.to_numeric(df['quantity'] * df['product_price'], errors='coerce')
df['revenue']

0        1949.97
1        2599.96
2        3249.95
3         649.99
4         649.99
          ...
56038     914.62
56039     914.62
56040     914.62
56041     914.62
56042     914.62
Name: revenue, Length: 56043, dtype: float64

## Summarize Data

➡️ Assignment Tasks
- Display the average price per product line
- Display the total revenue for all months

In [ ]:
#average price

In [ ]:
#total revenue